# Generated by Django 4.0 on 2022-03-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0006_alter_leadnotes_is_electric_layout_and_more'),
        ('Installation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_des', models.TextField()),
                ('appointment_date', models.DateField()),
                ('timeslot', models.CharField(blank=True, max_length=120, null=True)),
                ('device', models.CharField(blank=True, max_length=120, null=True)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='SalesApp.leadmodel')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
