# Generated by Django 4.0 on 2022-03-06 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0002_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='skromanclients',
            name='status',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
