# Generated by Django 4.0 on 2022-03-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0006_alter_leadnotes_is_electric_layout_and_more'),
        ('Installation', '0004_alter_skromanclients_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_des', models.TextField()),
                ('appointment_date', models.DateField()),
                ('timeslot', models.CharField(blank=True, max_length=120, null=True)),
                ('device', models.CharField(blank=True, max_length=120, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='SalesApp.leadmodel')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.RemoveField(
            model_name='skromanclients',
            name='status',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
