# Generated by Django 4.0 on 2022-02-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('c_type', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('contact', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=60, null=True)),
                ('sales_user', models.CharField(blank=True, max_length=1000, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients_details',
            },
        ),
        migrations.CreateModel(
            name='SkromanClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('c_type', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('contact', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=60, null=True)),
                ('sales_user', models.CharField(blank=True, max_length=1000, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skroman_clients',
            },
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(blank=True, max_length=40, null=True)),
                ('leads', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('billing_address', models.CharField(blank=True, max_length=140, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=140, null=True)),
                ('note_comment', models.CharField(blank=True, max_length=400, null=True)),
                ('next_followup', models.CharField(blank=True, max_length=60, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('status_lead', models.CharField(blank=True, max_length=10, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=40, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=40, null=True)),
                ('sales_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='AdminApp.users')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
    ]
