# Generated by Django 4.0 on 2022-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0003_leadnotes_ctime_leadnotes_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadnotes',
            name='is_demo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
