# Generated by Django 4.0 on 2022-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0005_alter_leadnotes_is_site_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadnotes',
            name='is_electric_layout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadnotes',
            name='is_lead_conform',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadnotes',
            name='is_proposal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
