# Generated by Django 4.0 on 2022-03-07 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0005_complaintsmodel_remove_skromanclients_status_and_more'),
        ('SalesApp', '0006_alter_leadnotes_is_electric_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='client',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='Installation.skromanclients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
