# Generated by Django 4.0 on 2022-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0007_leadmodel_client_leadmodel_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='ref_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='ref_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
